### ISSUE TITLE
"Copy Path" crash

### ISSUE THREAD

**Issue by hugolowegren** [Flow-Launcher/Flow.Launcher.Plugin.Everything#37]
"Copy Path" appears to throw an exception and not be set if the clipboard isn't empty.
I thought it had something do to with windows 10s "Clipboard History" feature (sync is off), but it occurs even when it's off.

Plugin version: v1.5.4
Everything version: 1.4.1.1009 (latest)
Flow Launcher version: 1.8.3

After some research i did find that changing Main.cs line 331 to `Clipboard.SetDataObject(record.FullPath,true);` appears to fix it. Though I'm not sure if changing that brings any other unwanted side effects.

Exception:

Flow Launcher version: 1.8.3
OS Version: Microsoft Windows NT 10.0.19042.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/25/2021 21:03:23
Exception:
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at Flow.Launcher.Plugin.Everything.Main.<>c__DisplayClass12_0.<LoadContextMenus>b__1(ActionContext context) in D:\a\Flow.Launcher.Plugin.Everything\Flow.Launcher.Plugin.Everything\Main.cs:line 331
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_7(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 190
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at Flow.Launcher.MainWindow.OnPreviewMouseButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 240
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
yep that's the cause of the issue. i remmember we had similar thing in flow's plugin and changed it to use Clipboard.SetDataObject call (https://github.com/Flow-Launcher/Flow.Launcher/search?q=SetDataObject). Did you want to give it a go pr this or would like me to?

**Comment by hugolowegren** [comment]
Might be a little while until I'll be able to so you can do it 👍
Thanks for the response!
